"""Q15) What is the purpose of the try block in Python error handling?

ans- The purpose of the try block in Python error handling is to enclose the code that might raise an exception.By enclosing this code within a try block, you can catch and handle exceptions gracefully.
If an exception occurs within the try block, Python will immediately jump to the appropriate except block that matches the type of exception raised. This allows you to handle the exception in a controlled manner, rather than letting it crash the program."""